# This is a basic workflow to help you get started with Actions

name: Hexo Auto-Build CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ hexo ]
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository Hexo branch
        uses: actions/checkout@v2
        with:
          ref: hexo
      
      # from: https://github.com/actions/setup-node
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      # install pandoc
      - name: install pandoc
        run: |
          sudo apt-get install pandoc
      
      # from: https://github.com/x-cold/yuque-hexo
      - name: Setup Hexo Dependencies and Generate Public Files
        env:
          YUQUE_TOKEN: ${{secrets.HEXO_DEPLOY_TOKEN}}
        run: |
          npm install hexo-cli -g
          npm install yuque-hexo -g
          npm install
          npm run start
          
      # from https://github.com/peaceiris/actions-gh-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: master
          publish_dir: ./public
        
          
         
        
    
